### ISSUE TITLE
your panel is broken in it's current state

### ISSUE THREAD

**Issue by drhax9908** [will2therich/FlarePanel#9]
Currently, admins cannot login to the admin panel, the error it gave me was my user array number and it said that the username/password was incorrect, which it wasn't. It only gave the array number on a valid login, also, the sql file gives an error about p_salt upon installing this panel from a fresh install. Please fix these issues, as I wish to try this panel

**Comment by will2therich** [comment]
Hi @drhax9908 

I have had a look into this and there was small typo in the 0.58.sql file.
I have now fixed this.

The error on the admin login page is due to that page not being finished yet.
The user login page doesn't experience the same issues

Please try reinstalling the panel.

Many thanks,
Will
